"""create basic tables

Revision ID: 9fcba9b2e446
Revises: 
Create Date: 2023-11-13 19:47:11.784738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fcba9b2e446'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Assets',
        sa.Column('AssetID', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('AssetType', sa.String(length=255), nullable=False),
        sa.Column('Name', sa.String(length=255), nullable=False),
        sa.Column('CreatedAt', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
        sa.Column('CreatedBy', sa.String(length=255), nullable=True),
        sa.Column('LastModified', sa.DateTime(), nullable=True),
        sa.Column('AdditionalAttributes', sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint('AssetID')
    )
    op.create_table('AssetRelationships',
        sa.Column('RelationshipID', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('ParentAssetID', sa.Integer(), nullable=True),
        sa.Column('ChildAssetID', sa.Integer(), nullable=True),
        sa.Column('RelationshipType', sa.String(length=255), nullable=False),
        sa.ForeignKeyConstraint(['ChildAssetID'], ['Assets.AssetID'], ),
        sa.ForeignKeyConstraint(['ParentAssetID'], ['Assets.AssetID'], ),
        sa.PrimaryKeyConstraint('RelationshipID')
    )
    op.create_table('CustomFields',
        sa.Column('CustomFieldID', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('AssetID', sa.Integer(), nullable=True),
        sa.Column('FieldName', sa.String(length=255), nullable=False),
        sa.Column('FieldValue', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['AssetID'], ['Assets.AssetID'], ),
        sa.PrimaryKeyConstraint('CustomFieldID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('CustomFields')
    op.drop_table('AssetRelationships')
    op.drop_table('Assets')
    # ### end Alembic commands ###